# NumPy Fundamentals

In [1]:
import numpy as np

## Indexing

In [7]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a
#2D array

array([[1, 2, 3],
       [4, 5, 6]])

### Specific Values

In [8]:
array_a[0] #2 = error 

array([1, 2, 3])

In [11]:
array_a[0][1]

2

In [12]:
array_a[1,0]

4

In [14]:
array_a[:,0]   #this is called slicing

array([1, 4])

### Negative Indices

In [18]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [19]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
array_a[-1]

array([4, 5, 6])

In [21]:
array_a[-1,-1]

6

## Assigning Values

In [22]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a
#2D array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
array_a[0,2] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [27]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [28]:
array_a[:,0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [29]:
list_a = [8,7,8]
array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [30]:
type(array_a[0])

numpy.ndarray

In [33]:
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [34]:
array_a = 9

In [35]:
type(array_a)

int

In [36]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Elementwise Properties

In [40]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [41]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
array_a * 2

## Multiplying each element of array_b by 2

array([14, 16, 18])

In [45]:
list_a = [1,2,3]
list_a + [2]

## Since lists don't work elementwise, we're concatenating [2] to list_a.

[1, 2, 3, 2]

In [48]:
array_a + 2

## Elementwise addition adds 2 to each element of array_a.

array([ 9, 10, 11])

In [49]:
array_a * array_b[1]

## Elementwise multiplication. 
## We multiply each individual element of array_a by its corresponding element in the second row of array_b.

array([28, 40, 54])

In [50]:
array_b - array_a

## The order of the elements matters for elementwise subtraction, division, as well as other operations. 

array([[-6, -6, -6],
       [-3, -3, -3]])

## Types of Data Supported by NumPy

In [51]:
array_a = np.arrayay([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float16)
array_a

# Defining all the values as floats (decimals).

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [53]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a

# Defining all the values as complex numbers.

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [54]:
array_a = np.array([[1,2,0],[4,5,6]], dtype = np.bool)
array_a

# Defining all the values as Booleans.

<ipython-input-54-d1909a485020>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a = np.array([[1,2,0],[4,5,6]], dtype = np.bool)


array([[ True,  True, False],
       [ True,  True,  True]])

In [55]:
array_a = np.array([[10,2,3],[4,5,6]], dtype = np.str)
array_a

# Defining all the values as text.

<ipython-input-55-e95068195692>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a = np.array([[10,2,3],[4,5,6]], dtype = np.str)


array([['10', '2', '3'],
       ['4', '5', '6']], dtype='<U2')

https://numpy.org/devdocs/reference/generated/numpy.dtype.kind.html <- <i> A link to the documentation explaining the unicode abbreviation.

## Characteristics of NumPy Functions

### Universal Functions

https://numpy.org/devdocs/reference/ufuncs.html <- <i> A link to the documentation page on Universal Functions

### Broadcasting

In [56]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [57]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [58]:
matrix_C = np.array([[1,2,3],[4,5,6]])
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.add(array_a, matrix_C)

## Adding up values, even though the arrays don't have matching shapes. 

array([[2, 4, 6],
       [5, 7, 9]])

In [59]:
np.add(array_b, matrix_C)

## Adding up values, even though the arrays don't have matching shapes. 

array([[2, 3, 4],
       [6, 7, 8]])

### Type Casting

In [61]:
np.add(array_b, matrix_C, dtype = np.float64)

## We can define the datatyep

array([[2., 3., 4.],
       [6., 7., 8.]])

### Running over an Axis

In [63]:
np.mean(matrix_C, axis = 0)

## Axis = 0 runs the function over every column. 
## Axis = 1 runs the function over every row. 

array([2.5, 3.5, 4.5])

In [64]:
np.mean(matrix_C, axis = 1)

## Axis = 0 runs the function over every column. 
## Axis = 1 runs the function over every row. 

array([2., 5.])

In [65]:
matrix_C 

array([[1, 2, 3],
       [4, 5, 6]])