# Working with Arrays

In [1]:
import numpy as np

## Slicing

In [4]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

### Basic Slicing

In [5]:
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
matrix_A[0:0]

array([], shape=(0, 3), dtype=int32)

In [7]:
matrix_A[0:1]

array([[1, 2, 3]])

In [8]:
matrix_A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix_A[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
matrix_A[:1]

array([[1, 2, 3]])

In [11]:
matrix_A[1:]

array([[4, 5, 6]])

In [12]:
matrix_A[2:]

array([], shape=(0, 3), dtype=int32)

In [13]:
matrix_A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix_A[:1]

In [14]:
matrix_A[1]

array([4, 5, 6])

In [15]:
matrix_A[:-1]

array([[1, 2, 3]])

In [16]:
matrix_A[:,1:]

array([[2, 3],
       [5, 6]])

In [17]:
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
matrix_A[1:,1:]

array([[5, 6]])

### Stepwise Slicing

In [19]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [20]:
matrix_B[:,:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [21]:
matrix_B[::,::]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [22]:
matrix_B[::2,::]

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [23]:
matrix_B[::,::2]

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [24]:
matrix_B[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [25]:
matrix_B[::-2,::2]

array([[4, 3, 0],
       [1, 1, 0]])

In [26]:
matrix_B[-1::-2,::2]

array([[4, 3, 0],
       [1, 1, 0]])

In [27]:
matrix_B[-1::-1,::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

### Conditional Slicing

In [28]:
matrix_C = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [29]:
matrix_C[:,0] #slice first column

array([1, 3, 4])

In [30]:
matrix_C[:,0] > 2

array([False,  True,  True])

In [ ]:
matrix_C[:,0] > 2

In [31]:
matrix_C[:,:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [32]:
matrix_C[matrix_C[:,:] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [33]:
matrix_C[matrix_C[:,:] == 2]

array([2])

In [35]:
matrix_C[matrix_C[:,:] >= 2]

array([2, 3, 6, 6, 7, 4, 4, 5, 3, 8])

In [36]:
matrix_C[matrix_C[:,:] != 2]

array([1, 1, 1, 0, 3, 6, 6, 7, 4, 4, 5, 3, 8, 0])

In [38]:
matrix_C[matrix_C[:,:] % 2 == 0]

array([2, 0, 6, 6, 4, 4, 8, 0])

In [39]:
matrix_C[(matrix_C[:,:] % 2 == 0) & (matrix_C[:,:] <= 4)  ]

array([2, 0, 4, 4, 0])

## Dimensions and the Squeeze Function

In [52]:
matrix_D = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [53]:
type(matrix_D[0,0])

numpy.int32

In [54]:
print(matrix_D[0,0])

1


In [55]:
type(matrix_D[0,0:1])

numpy.ndarray

In [56]:
print(matrix_D[0,0:1])

[1]


In [57]:
print(matrix_D[0:1,0:1])

[[1]]


In [58]:
type(matrix_D[0:1,0:1])

numpy.ndarray

In [59]:
print(matrix_D[0,0].shape)
print(matrix_D[0,0:1].shape)
print(matrix_D[0:1,0:1].shape)

# Same value stored in 3 different ways -> 0-D, 1-D and 2-D array

()
(1,)
(1, 1)


In [60]:
matrix_D[0:1,0:1].squeeze()

array(1)

In [61]:
type(matrix_D[0:1,0:1].squeeze())

numpy.ndarray

In [64]:
matrix_D[0:1,0:1].squeeze().shape

()

In [66]:
 print(matrix_D[0:1,0:1].squeeze())

1


In [68]:
np.squeeze(matrix_D[0:1,0:1])

array(1)

In [69]:
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

## All excess dimensions are lost and our outputs are aligned. 

()
()
()
